# Generated by Django 4.2.7 on 2025-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_available',
        ),
        migrations.AddField(
            model_name='picture',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_for_sale', 'Not For Sale'), ('discuss_pricing', 'Discuss Pricing')], default='available', help_text='Available: price displayed. Not For Sale: price hidden. Discuss Pricing: price hidden, buyer should contact owner.', max_length=20),
        ),
    ]
