# Generated by Django 4.2.7 on 2025-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_picture_is_available_picture_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
        migrations.AddField(
            model_name='picture',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='gallery.category'),
        ),
    ]
